Hw1
olgalupuleac/SoftwareDesign pull request #1
Opened 2019-02-07 19:12 UTC by olgalupuleac

2019-02-18 02:24 UTC, ArtyomLobanov requested changes
1. Если не нашлось файла в cat или внешняя команда завершилась с ошибкой, не нужно ронять интерпретатор. Просто выведите сообщение об ошибке в понятной пользователю форме и ожидайте следующей команды.
2. Ругайтесь на неправильные кавычки или пайпы:
```
echo "text
| echo text | |cat |
```
3. Добавьте интеграцию с [Travis](https://travis-ci.org)

2019-02-18 02:24 UTC, ArtyomLobanov commented on hw1/README.md
> +
У вас что-то не то с форматированием текста. С GitHub-а читать не удобно. Особенно 

> под-становки

 радуют)

2019-02-18 02:24 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/Interpreter.scala
> +    val lexer = new Parser(scope)
lexer = parser? Что-то тут не так

2019-02-18 02:24 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/Interpreter.scala
> +          args += token
А вот это всё как раз работа парсера. Зачем это здесь?

2019-02-18 02:24 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/commands/Command.scala
> +case class Stdin(text: String) extends Input {
Назовите как-нибудь человекочитаемо - чтобы название отражало суть класса.

2019-02-18 02:24 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/commands/Command.scala
> +    val res = file.getLines.mkString("\n")
System.lineSeparator()

2019-02-18 02:24 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/commands/WcCommand.scala
> +  def numberOfWords(str: String): Int = str.split("\\s").length
Плохой разделитель. Подумайте, когда это приводит к ошибке в количестве слов.

2019-02-18 02:24 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/commands/WcCommand.scala
> +  def numberOfBytes(str: String): Int = str.getBytes().length
Из-за того, что при чтении файла портятся окончания строк, результат получается неверный. Используйте лучше готовые решения, например, [File.length](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#length--)

2019-02-19 10:26 UTC, olgalupuleac commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/Interpreter.scala
> +          args += token
Мне кажется, что там нужно два прохода. То, что у меня делает парсер -- это разбор кавычек и подстановка переменных окружения. То есть `e'c'$x "56"` превращается в `echo, 56` (если `x=ho`) А после этого нужно понять, что является командой, что -- присвоением переменной окружения, а что -- аргументом. Bash на такую строчку `s=1 echo x=9 | y=5 cat
`, например, выдаёт `x=9`. Но мне кажется, что если пытаться ещё в парсере всё это делать, то нужно будет вводить дополнительные состояния конечного автомата (присвоение, команда, аргумент), никак не связанные с предыдущими (типы кавычек), и всё станет чересчур сложно.

2019-03-04 17:04 UTC, ArtyomLobanov requested changes
1. Хорошо, что стали следить за кавычками и пайпами, но то, что из-за ошибок в формате команды падает интерпретатор - это уже немного перебор. Достаточно сообщения об ошибке.
```
echo "fdc
[error] (run-main-0) java.lang.IllegalArgumentException: Syntax error: unclosed quote
[error] java.lang.IllegalArgumentException: Syntax error: unclosed quote
[error]         at ru.spbau.lupuleac.cli.Parser.splitLineToTokens(Parser.scala:161)
[error]         at ru.spbau.lupuleac.cli.Interpreter.apply(Interpreter.scala:37)
<..>
```

2019-03-04 17:04 UTC, ArtyomLobanov commented on src/main/scala/ru/spbau/lupuleac/cli/commands/WcCommand.scala
> +      return Try(List(str.split(System.lineSeparator()).length, str.split("[\\s]+").length, str.getBytes().length).mkString(" "))
Разделитель исправили, но всё ещё есть проблемы с числом слов. [Дарю](https://github.com/olgalupuleac/SoftwareDesign/files/2927353/test.txt)

2019-03-11 15:50 UTC, ArtyomLobanov reviewed
@yurii-litvinov

2019-03-11 15:50 UTC, ArtyomLobanov commented on src/main/scala/ru/spbau/lupuleac/cli/commands/WcCommand.scala
> +        List(str.split(System.lineSeparator()).length, str.split("[\\s]+").count(s => s.nonEmpty), str.getBytes().length).mkString(" ")
Следите за длиной строк, пожалуйста

2019-03-11 15:50 UTC, ArtyomLobanov commented on src/test/scala/ru/spbau/lupuleac/cli/commands/CommandTest.scala
>        "5 5 21 src/test/resources/several_lines", "6 7 32 total")
Git подменяет окончания строк в файлах на те, которые используются в конкретной операционной системе. Из-за этого размер файла меняется и тест падает.

2019-03-11 16:35 UTC, olgalupuleac commented on src/main/scala/ru/spbau/lupuleac/cli/commands/WcCommand.scala
> +        List(str.split(System.lineSeparator()).length, str.split("[\\s]+").count(s => s.nonEmpty), str.getBytes().length).mkString(" ")
Почему-то автоформатирование в Idea не работает, по крайней мере у меня для Scala :(

2019-03-11 17:37 UTC, olgalupuleac commented on src/test/scala/ru/spbau/lupuleac/cli/commands/CommandTest.scala
>        "5 5 21 src/test/resources/several_lines", "6 7 32 total")
У меня сейчас работает тот тест, который есть, под Виндой. Возможно, у меня как-то по-другому настроен git. Мне лучше получать фактический размер файла в тесте с помощью File.lenght()?

2019-03-11 17:43 UTC, ArtyomLobanov commented on src/test/scala/ru/spbau/lupuleac/cli/commands/CommandTest.scala
>        "5 5 21 src/test/resources/several_lines", "6 7 32 total")
Забавно. Да, давайте получать размер через File.length

2019-03-18 12:39 UTC, yurii-litvinov approved these changes
Я бы сказал дополнить комментарии и  описание, но поскольку всё остальное выглядит прилично, не придираюсь, зачтена.

2019-03-18 12:39 UTC, yurii-litvinov commented on README.md
> +![GitHub Logo](bash.png)
Если считать, что это диаграмма классов, то она довольно ужасна :) Например, стрелки реализации не в ту сторону, практически все связи --- use. Однако в первой домашке предполагалась диаграмма "как умеете", так что не придираюсь.

2019-03-18 12:39 UTC, yurii-litvinov commented on src/main/scala/ru/spbau/lupuleac/cli/Parser.scala
> +sealed trait Token
Этой штуке по идее тоже нужен комментарий

2019-03-18 12:39 UTC, yurii-litvinov commented on src/main/scala/ru/spbau/lupuleac/cli/commands/Command.scala
> +  def get: String
Комментарии тут даже важнее, чем к конкретным классам, потому как этой штукой потом много где пользуются, и неплохо бы знать, что конкретно означает каждый метод или свойство.

2019-03-18 12:39 UTC, yurii-litvinov commented on README.md
> +После этого токены должны быть интерпретированы как команды, присвоения и аргументы.
Как нарисовать сову? Нарисовать два кружка и всё остальное. Так же и тут, как работает система --- сначала мы парсим, потом всё остальное делаем :)

2019-03-21 14:32 UTC, merged