Hw2
olgalupuleac/SoftwareDesign pull request #2
Opened 2019-02-12 17:48 UTC by olgalupuleac

2019-03-13 13:29 UTC, ArtyomLobanov requested changes
1. Вы слишком много на себя берёте - большая часть функциональности уже реализована в [стандартной библиотеке](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html). Для отключения чувствительности к регистру есть специальный флаг, а для матчинга границ слова специальное обозначение \b.
2. Если файла нет, достаточно вывести пользователю сообщение об ошибке. Ронять интерпретатор не нужно

2019-03-13 13:29 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/commands/GrepCommand.scala
> +  val ignoreCase: ScallopOption[Boolean] = toggle(name = "ignore-case", default = Some(false), descrYes = "Ignore case distinctions in both the PATTERN and the input files.")
Следите за длиной строк, пожалуйста

2019-03-13 13:29 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/commands/GrepCommand.scala
> +    val pattern = if (conf.ignoreCase()) conf.pattern().toLowerCase.r else conf.pattern().r
Не-не-не, регэксп нельзя приводить к нижнему регистру - от этого его смысл может измениться. 
Например, \S матчит любой непробельный символ, а \s наоборот любой пробельный. Смотрите
```cmd
>cat .gitignore | grep \S
.idea
dist/*
target/
lib_managed/
src_managed/
project/boot/
project/plugins/project/
.history
.cache
.lib/
>cat .gitignore | grep \s
*пустая строка*
```
Всё работает как надо. А теперь то же самое, но с ключом -i
```cmd
cat .gitignore | grep -i \s
*пустая строка*
cat .gitignore | grep -i \S
*пустая строка*
```
Как видите, всё сломалось :(

2019-03-13 13:29 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/commands/GrepCommand.scala
> +  def matchWord(pattern: Regex, line: String): Boolean = {
Смысл ключа -w в стандартном grep в том, что заданный регэксп не матчит какие-то крайние слова частично. Например,
```cmd
$ echo "some text" | grep "me text"
some text
>echo "some text" | grep -w "me text"
*ничего*
```
Но в целом под паттерн может попадать несколько слов
```cmd
>echo "so me text" | grep -w "me text"
so me text

```

2019-03-13 13:29 UTC, ArtyomLobanov commented on hw1/src/main/scala/ru/spbau/lupuleac/cli/commands/GrepCommand.scala
> +    res.mkString("\n")
System.lineSeparator()

2019-03-13 13:29 UTC, ArtyomLobanov commented on hw1/LIBRARY.md
> +Была выбрана библиотека `scallop` из-за удобства использования и наличия всего необходимого функционала.
Можно немножко подробнее. Чем вас не устроили остальные варианты?

2019-03-15 09:21 UTC, ArtyomLobanov requested changes
Убедительно 
![image](https://user-images.githubusercontent.com/9067686/54419913-b486d300-4719-11e9-8cef-d041467a9679.png)
Хорошо, что проверяется корректность аргументов, но достаточно выводить пользователю сообщение об ошибке. Ронять интерпретатор не нужно
```
grep -A -10 pattern file
grep -A dva pattern file
```

2019-03-15 09:21 UTC, ArtyomLobanov commented on src/main/scala/ru/spbau/lupuleac/cli/commands/GrepCommand.scala
> +    }
Где-то тут должна быть проверка, что если строка не матчится, но afterContext не 0, то всё равно вывести.
Не зря же вы его передаёте)

2019-03-22 18:30 UTC, ArtyomLobanov commented
Не то, чтобы очень понятное сообщение об ошибке, но...
```cmd
>grep -A ed . .gitignore
For input string: "ed"
```

Ок @yurii-litvinov

2019-03-25 11:55 UTC, yurii-litvinov approved these changes
Всё ок, зачтена

2019-03-25 12:19 UTC, merged